### ISSUE TITLE
Sampling Rate

### ISSUE THREAD

**Issue by jamrader** [krafter/DetectingAudioFrequency#2]
If I'm not mistaking you only sample the audio input about every 3 seconds for the max Hz. Is there a way I can increase this? Say to sampling the incoming audio for the max Hz fifteen times a second?

**Comment by jamrader** [comment]
Ahh. OK, so the default is roughly very 3 seconds. It can be changed by changing the value of this variable:
const UInt32 accumulatorDataLenght

I guess my question now is, are these the only valid options:

//16384; //32768; 65536; 131072;

**Comment by Greg767** [comment]
AFAIK no. I use at the moment 2048, but I've read somewhere that its less precise with lower values. I don't really know what "less precise" means.

**Comment by jamrader** [comment]
That's what I ended up using as well. 2048.

**Comment by jamrader** [comment]
I'm having trouble including the files in my own project. Specifically, I'm getting errors like this:

"_glFrustumf", referenced from:
      MoGfx::perspective(double, double, double, double) in mo_gfx.o
  "_glHint", referenced from:
      MoGfx::perspective(double, double, double, double) in mo_gfx.o
  "_glLoadIdentity", referenced from:
      MoGfx::perspective(double, double, double, double) in mo_gfx.o
      MoGfx::ortho(int, int, int) in mo_gfx.o

Is there something I'm missing I need to do to include .mm files?

**Comment by Greg767** [comment]
Unfortunately I cannot help with that, because I didn't need the visualisation part, only the frequency calculations. Do you have problems with other methods, outside of MoGfx?

**Comment by jamrader** [comment]
It was my own fault. I messed up somehow adding the frameworks. Something about dragging them from one xcode project to my own (rather than add them in Linked Frameworks and Libraries), possibly by copying them--I'm not sure--created the issue. 

The issue I do have now is this error happens about 40% of the time the page opens:

ERROR:     [0x19ab17310] >aurioc> 806: failed: -50 (enable 3, outf< 2 ch,  44100 Hz, Int8.24, non-inter> inf< 2 ch,  44100 Hz, Int8.24, non-inter>)
2015-06-26 11:35:36.634 Lancers[3189:626276]  error = couldn't setup remote i/o unit
2015-06-26 11:35:36.635 Lancers[3189:626276]  MoAudio init ERROR
2015-06-26 11:35:36.635 Lancers[3189:626276]  MoAudio start ERROR

Thank you for all your help and for your great iOS contribution.

**Comment by krafter** [comment]
That's right, const UInt32 accumulatorDataLenght - is how much data you accumulate before computing the FFT. Dividing this value by sample rate (fps) gives you the seconds. You can put any value there, but values must be the int power of 2. (2,4,8,16,32,64 so on). And yes, the less samples you have accumulated the less precise is the result. The good thing is you can choose any precision you need by accumulating the proper amount of frames. 
So for example you have a range of 0-22050 HZ to detect in. Passing 2046 frames in will give you 1024 values. Each value corresponds a part of your 0-22050 range. Obviously you can not detect with 1 HZ precision here, just because you only have 1024 possible "options". So your precision here is 22050/1024 = 21.53 HZ (error is within 21.53 HZ).
